.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "UBUNTU\-LOCATION\-SERVICE" "2" "May 2013" "ubuntu" ""
.
.SH "NAME"
\fBubuntu\-location\-service\fR \- A location service aggregating position/velocity/heading updates and exporting them over dbus\.
.
.SH "SYNOPSIS"
\fBubuntu\-location\-service\fR \fB\-\-bus\fR \fIwell known bus name\fR \fB\-\-provider\fR \fIprovider\fR [\fB\-\-provider\fR \fIprovider\fR] [provider specific options]
.
.SH "DESCRIPTION"
A location service aggregating position/velocity/heading updates and exporting them over dbus\.
.
.SH "OPTIONS"
These options control which bus the service is exposed upon and which providers are instantiated:
.
.TP
\fB\-\-bus\fR=\fIbus\fR
Specify the bus that the service should be exposed upon, valid values are "session" or "system"\.
.
.TP
\fB\-\-provider\fR=\fIprovider\fR
Specify the provider that should be instantiated and configured for this service instance\. Valid values are: geoclue::Provider, gps::Provider and skyhook::Provider\.
.
.P
These options control the behavior of the geoclue provider:
.
.TP
\fB\-\-geoclue::Provider::name\fR=\fIname\fR
The name of the provider on the bus\.
.
.TP
\fB\-\-geoclue::Provider::path\fR=\fIpath\fR
The object path of the provider on the bus\.
.
.P
These options control the behavior of the Skyhook provider:
.
.TP
\fB\-\-skyhook::Provider::username\fR=\fIusername\fR
Username for authenicating with the Skyhook service\.
.
.TP
\fB\-\-skyhook::Provider::realm\fR=\fIrealm\fR
Realm for authenticating with the Skyhook service\.
.
.TP
\fB\-\-skyhook::Provider::period\fR=\fIperiod\fR
Delay between updates in [ms]\.
.
.P
These options control the logging behavior of the service:
.
.TP
\fB\-\-logtostderr\fR=<boolean, default: false>
Log messages to stderr instead of logfiles, defaults to false\.
.
.TP
\fB\-\-stderrthreshold\fR=<threshold, default: 2>
Copy log messages at or above this level to stderr in addition to logfiles\. The numbers of severity levels INFO, WARNING, ERROR, and FATAL are 0, 1, 2, and 3, respectively\. Defa
.
.TP
\fB\-\-minloglevel\fR=<level, default: 0>
Log messages at or above this level\. Again, the numbers of severity levels INFO, WARNING, ERROR, and FATAL are 0, 1, 2, and 3, respectively\.
.
.TP
\fB\-\-log_dir\fR=<path, default: "">
If specified, logfiles are written into this directory instead of the default logging directory\.
.
.TP
\fB\-\-v\fR=<level, default: 0>
Show all VLOG(m) messages for m less or equal the value of this flag\.
.
.SH "EXAMPLES"
Starting the service with a gps and a skyhook provider, exposing it on the system bus:
.
.IP "" 4
.
.nf

$ /usr/bin/ubuntu\-location\-service/examples/service
    \-\-bus system
    \-\-provider gps::Provider
    \-\-provider skyhook::Provider
    \-\-skyhook::Provider::username=ut_testing
    \-\-skyhook::Provider::realm=ut_testing\.com
.
.fi
.
.IP "" 0
.
.P
A slightly more verbose instance:
.
.IP "" 4
.
.nf

$ /usr/bin/ubuntu\-location\-service/examples/service
  \-\-logtostderr=true
  \-\-v=5
  \-\-bus system
  \-\-provider gps::Provider
  \-\-provider skyhook::Provider
  \-\-skyhook::Provider::username=ut_testing
  \-\-skyhook::Provider::realm=ut_testing\.com
.
.fi
.
.IP "" 0
.
.SH "COPYRIGHT"
Ubuntu Location Service is Copyright (C) 2012 Canonical Ltd\.
